module.exports = {
  "ALIVE_IMG": "https://files.catbox.moe/nlnk1p.jpg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "private",
  "BOT_NUMBER": "923043788282",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": false,
  "AUTO_VOICE": false,
  "AUTO_STICKER": true,
  "AUTO_REPLY": false,
  "AUTO_REACT": true,
  "WELCOME": true,
  "ANTI_BAD": true,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ALLWAYS_ONLINE": false,
  "MOROCCO_BLOCK": false,
  "BTN_MSG": false,
  "OWNER_NAME": "MR SHABAN",
  "NEWS_JID": "923043788282@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": false,
  "AUTO_NEWS": false
};
